### ISSUE TITLE
Formatting and cleanup

### ISSUE THREAD

**Issue by wrussell1999** [wrussell1999/food-flex-discord#5]
- Rename `server_id` to `guild_id`
- Change the use of `is` to `==` as we're not comparing objects, but the data itself
- Reduce number of methods used
- Move hardcoded strings into `strings.json`
- Group more commands
    - Improve the names of commands
    - Add descriptions to all the commands
- Improve packages (maybe more or different names?)

**Comment by wrussell1999** [comment]
- Rename `server_id` to `guild_id` :heavy_check_mark: 
- Change the use of `is` to `==` as we're not comparing objects, but the data itself :hammer_and_pick: 
- Reduce number of methods used :hammer_and_pick: 
- Move hardcoded strings into `strings.json` :negative_squared_cross_mark: 
- Group more commands :negative_squared_cross_mark: 
    - Improve the names of commands
    - Add descriptions to all the commands
- Improve packages (maybe more or different names?) :heavy_check_mark:

**Comment by wrussell1999** [comment]
New addition:
when `flex:close_submissions` is used, it disables attachments from the channel, preventing people from submitting.

**Comment by danielfspencer** [comment]
61474a423b083e51574b2b2f625ddf02708da223 Remove a few cases of ```is True``` and replace list comprehensions with more readable loops

**Comment by danielfspencer** [comment]
Another todo:
* Don't pollute namespace by importing specific methods from other modules, instead import entire module for readability

**Comment by danielfspencer** [comment]
The following commits convert all module imports into the more readable verison of importing the entire module:

194936b3c6af10f71e1bac83ba67aeecad049520
95e2553d7d896828bc405e7d3adc7ec2782fa4af
ea6d2fd5c5936fe01e704983a35a5d004eeb8f71

**Comment by danielfspencer** [comment]
a56726f911f4aeb3bcd48aa122b425219e20d7a5 Makes logging more readable
