### ISSUE TITLE
Vote handling

### ISSUE THREAD

**Issue by wrussell1999** [wrussell1999/food-flex-discord#6]
In the `data` branch, we are moving from using lists to dictionary per user. The structure looks like this:

```json
"user_unique_id": {
    "nick": "Will",
    "submitted": false,
    "voted": true,
    "votes": 0,
    "vote_index": null
}
```

`vote_index` needs to be changed to a more reliable, and readable solution. Also, `votes` will be set to 0 for everyone by default.

When someone submits, it creates a dictionary for them. When someone votes, it creates a dictionary for them, if one doesn't already exist. Just got to make sure that when the results are posted, it only posts the people who submitted (check the submitted field).

**Comment by danielfspencer** [comment]
80e764bab77bb9ee56547e3c3ebe2082046dbe37 fixes this by removing ```vote_index```
