### ISSUE TITLE
Repost submission pictures at voting

### ISSUE THREAD

**Issue by wrussell1999** [wrussell1999/food-flex-discord#9]
Submissions get the message ID and get the attachment URL. These are posted as one image, as all the images tiled with the letter on top.

**Comment by danielfspencer** [comment]
30294d5c3951db966e8fc9e2a45b87390d568885 lays the groundwork for this feature

**Comment by danielfspencer** [comment]
This feature is targeted for release in the upcoming v2.x.x series

**Comment by danielfspencer** [comment]
Release v2.0.0 8a5a735dd4a93fd44669a0d9868973a12710ae49 implements this, closing issue.
